// Built-in content for when story.json is missing or short a key.

export const WHITEBOARD = {
  how: 'Drag the boxes on. Drag from one box to another to connect them. Then send traffic.',
  timeLimitSec: 60,
  points: { survive: 200, secondTry: 120, fail: 30, secondsLeftBonus: 2 },
  runButton: 'Send traffic',
  pieces: {
    browser: { label: 'Browser', hint: 'Where the people are.' },
    cdn: { label: 'CDN', hint: 'Hands out the files that never change.' },
    loadBalancer: { label: 'Load balancer', hint: 'Shares the requests out.' },
    app: { label: 'App', hint: 'The code.' },
    app2: { label: 'App (second copy)', hint: 'The same code again, in case.' },
    cache: { label: 'Cache', hint: 'Remembers answers.' },
    queue: { label: 'Queue', hint: 'Holds work for later.' },
    worker: { label: 'Worker', hint: 'Does the slow jobs.' },
    database: { label: 'Database', hint: "The one thing you can't lose." },
  },
  puzzles: [
    {
      id: 'wb-builtin',
      title: 'Page to person',
      brief: 'A small site, a few hundred visitors. Keep the browser away from the database.',
      pieces: ['browser', 'cdn', 'app', 'database'],
      required: [
        ['browser', 'cdn'],
        ['cdn', 'app'],
        ['app', 'database'],
      ],
      optional: [['browser', 'app']],
      forbidden: [
        { edge: ['browser', 'database'], text: "The browser's talking straight to the database. That never ends well." },
        { edge: ['cdn', 'database'], text: 'The CDN is caching the database. Everybody gets the same row.' },
      ],
      missing: [
        { edge: ['browser', 'cdn'], text: 'No CDN in front. One box served every image and gave up.' },
        { edge: ['cdn', 'app'], text: "The CDN has nothing behind it. A blank page, delivered fast." },
        { edge: ['app', 'database'], text: "The app can't reach the database. It's guessing." },
      ],
      traffic: { label: '200 visitors', rps: 200, durationSec: 5 },
      success: 'Held. Nothing interesting happened, which is the point.',
    },
  ],
  defaultFailure: 'It fell over. Not sure where yet.',
  extraEdgeText: "That line isn't hurting anything. It isn't doing anything either.",
  timeout: "Out of time. Somebody else booked the room.",
};

export const REVIEW = {
  how: 'One line in each diff has a real bug. Click it before the timer runs out.',
  diffsPerRound: 3,
  secondsPerDiff: 18,
  lowEnergySecondsPerDiff: 14,
  points: { correct: 100, secondsLeftBonus: 3, wrong: -20, timeout: 0 },
  streak: { allCorrectBonus: 75, text: 'All of them. Requesting changes.' },
  copy: {
    correct: ['Found it.', "That's the one."],
    wrong: ["Not that one. That's just style."],
    timeout: 'Approved by timeout.',
  },
  diffs: [
    {
      id: 'rv-builtin-total',
      file: 'cartTotal.js',
      title: 'Add up the cart',
      kind: 'off by one',
      lines: [
        'function cartTotal(items) {',
        '  let total = 0;',
        '  for (let i = 0; i <= items.length; i++) {',
        '    total += items[i].price;',
        '  }',
        '  return total;',
        '}',
      ],
      bugLine: 2,
      explanation: 'The loop runs one past the end, so the last pass reads price off undefined and throws.',
      fix: '  for (let i = 0; i < items.length; i++) {',
    },
    {
      id: 'rv-builtin-await',
      file: 'saveDraft.js',
      title: 'Save the draft before closing',
      kind: 'unawaited promise',
      lines: [
        'async function closeEditor(draft) {',
        '  if (draft.dirty) {',
        '    storage.save(draft);',
        '  }',
        '  editor.close();',
        '}',
      ],
      bugLine: 2,
      explanation: "The save isn't awaited, so the editor closes before the draft is written.",
      fix: '    await storage.save(draft);',
    },
    {
      id: 'rv-builtin-assign',
      file: 'canDelete.js',
      title: 'Only admins can delete',
      kind: 'assignment in a condition',
      lines: [
        'function canDelete(user) {',
        "  if (user.role = 'admin') {",
        '    return true;',
        '  }',
        '  return false;',
        '}',
      ],
      bugLine: 1,
      explanation: 'One equals sign sets the role instead of checking it, so everybody is an admin now.',
      fix: "  if (user.role === 'admin') {",
    },
  ],
};
